### PR TITLE
Create Precautions

### PR DESCRIPTION
**Pull request by Samirbhajipale**

### CODE REVIEW

**Comment by FFY00** [comment]
@AZafar98 this is spam trying to get entries for https://hacktoberfest.digitalocean.com/.

It's unfortunate that initiatives like this, which should motivate people to do open source, are met with this kind of behavior.

Please label it as `invalid` so that it does not count towards their hacktoberfest PR count.

**Review by AZafar98 — CHANGES_REQUESTED** [review]
Invalid.

**Comment by AZafar98** [comment]
> @AZafar98 this is spam trying to get entries for https://hacktoberfest.digitalocean.com/.
> 
> It's unfortunate that initiatives like this, which should motivate people to do open source, are met with this kind of behavior.
> 
> Please label it as `invalid` so that it does not count towards their hacktoberfest PR count.

@FFY00 Thanks for the heads up.

**Comment by FFY00** [comment]
@AZafar98 no problem :+1: Unfortunately you have to add a Github label to the PR for it not to count.

**Comment by AZafar98** [comment]
@FFY00 My bad, thanks!

**Pull request closed without merging**
